// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package anonymous.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Anonymous module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_LoginBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Anonymous.DS_Login");
		return builder;
	}

	public static anonymous.proxies.Anonymous dS_Login(IContext context)
	{
		Object result = dS_LoginBuilder().execute(context);
		return result == null ? null : anonymous.proxies.Anonymous.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_User_Registration_Builder(
		anonymous.proxies.Anonymous _anonymous
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Anonymous.DS_User_Registration_");
		builder = builder.withParam("Anonymous", _anonymous);
		return builder;
	}

	public static void dS_User_Registration_(
		IContext context,
		anonymous.proxies.Anonymous _anonymous
	)
	{
		dS_User_Registration_Builder(
				_anonymous
			)
			.execute(context);
	}
}
