// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package product.proxies;

public enum Bricks_Enum
{
	Red_Bricks(new java.lang.String[][] { new java.lang.String[] { "en_US", "Red Bricks" } }),
	Flyash_Bricks(new java.lang.String[][] { new java.lang.String[] { "en_US", "Flyash Bricks" } }),
	Concrete_Blocks(new java.lang.String[][] { new java.lang.String[] { "en_US", "Concrete Blocks" } }),
	Hollow_Blocks(new java.lang.String[][] { new java.lang.String[] { "en_US", "Hollow Blocks" } }),
	AAC_Blocks(new java.lang.String[][] { new java.lang.String[] { "en_US", "AAC Blocks" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Bricks_Enum(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
